#!/bin/bash

## Use this-branch-is-merged to update master, then rename the current branch.
## Fails if already on master.

## Usage: git this-branch-is-merged

source "$(git --exec-path)/git-sh-setup"

set -e
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ "$current_branch" == 'master' ]] ; then
    echo "Currently on master.  Please run on another branch that has been merged into master."
    exit 10
fi

git update-master $@
git rename-merged "$current_branch"
