#!/bin/sh

## This script just checks out master, pulls master, then fetches and prunes branches

## Usage: git update-master

source "$(git --exec-path)/git-sh-setup"

USAGE=''
function _doitall {
    set -e
    git checkout master
    git pull
    git fetch -p
    set +e
}

_doitall
